[package]
authors = ["Michael Spencer <sonrisesoftware@gmail.com>"]
name = "aeropi"
publish = false
version = "0.1.0"

[dependencies]
ndarray = "*"
num = "*"
pid_control = "*"
serde = "*"
serde_derive = "*"
serde_yaml = "*"
